import type { EventAssessmentRow } from "@/lib/types";

export function assessmentRow(failed = false): EventAssessmentRow {
  return {
    assessment_id: "assessment-eur",
    pair: "EURGHS",
    as_of: "2026-10-02T12:00:00Z",
    created_at: "2026-10-02T12:04:00Z",
    expires_at: "2026-10-03T12:00:00Z",
    is_example: false,
    status: failed ? "failed" : "assessed",
    weekly_forecast_id: "weekly-eur",
    daily_forecast_id: "daily-eur",
    record: {
      pair: "EURGHS",
      as_of: "2026-10-02T12:00:00Z",
      calls: [],
      config: {},
      status: failed ? "failed" : "assessed",
      context: {
        pair: "EURGHS",
        as_of: "2026-10-02T12:00:00Z",
        is_example: false,
        daily: { origin: "2026-10-02", points: [] },
        weekly: { origin: "2026-09-28", points: [] },
        spots: [],
      },
      evidence: [],
      assessment: failed ? null : {
        pair: "EURGHS",
        decision: "hold",
        rationale: "Retain the weekly rate.",
        persistence: "uncertain",
        watch_items: [],
        evidence_ids: [],
        prior_reviews: [],
        recommendations: [],
        counter_evidence: [],
        evidence_strength: "low",
      },
      created_at: "2026-10-02T12:04:00Z",
      error_code: failed ? "invalid_structured_output_or_evidence" : null,
      expires_at: "2026-10-03T12:00:00Z",
      is_example: false,
      context_hash: "context-eur",
      assessment_id: "assessment-eur",
      prompt_version: "events-v2.8",
      prompt_snapshot: {},
      rejected_evidence: [],
      validation_errors: failed ? [{
        code: "semantic_validation",
        message: "Numerical recommendations require independently verified dated evidence",
        location: "",
      }] : [],
      adjustment_preview: [],
      publication_action: "retain_base",
      provider_final_text: null,
      memory_reference_map: {},
    },
  };
}
